name: Snyk Security Scan

on:
  push:
    branches:
      - main # Adjust this to your main branch

jobs:
  snyk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Run Snyk Security Scan
        env:
          SNYK_TOKEN: 31e14810-b07f-4f33-8f2b-0e2ff2419826
        run: snyk test --all-projects
